### ISSUE TITLE
Villagers?

### ISSUE THREAD

**Issue by Slashay** [MC-Minigames/BedWars#7]
Well, firstoff all this dont work with Citizens and I have tried manually spawning villagers but they get removed on start, also do you have to lace the bed yourself? Cause I seem to not be able to finish without someone leaving, I tried placing myself other team still can't break it. Also I get the Dubble Chat sometimes! 

EDIT: Also one more! Clay and Iron only spawn on one of the four places!

**Comment by Kaskadee** [comment]
You can place team beds with /bw setupbeds

**Comment by Slashay** [comment]
OK! I found out myself but one problem still remaining! Only the first clay and Iron I placed drops IRon and clay not the others
